### ISSUE TITLE
No feedback i given wether installtion was succesfull or not

### ISSUE THREAD

**Issue by freemint** [KaOSx/calamares#64] opened 2015-06-07 18:04 UTC

**Comment by demmm** [comment] 2015-06-07 19:35
http://kaosx.us/asking-and-reporting-the-smart-way/
Nothing here that states this is a bug report or what you are doing, what ISO used, how the ISO was created, how you setup the disk for the install, no install log that could show if anything went wrong or not.

**Comment by demmm** [comment] 2015-06-15 22:34
No further response from submitter, closing as not a bug report.

**Closed by demmm** 2015-06-15 22:34 UTC
