### ISSUE TITLE
Error in Boost.Python job bootldr in a Virtual Machine

### ISSUE THREAD

**Issue by FelixKainz** [KaOSx/calamares#80] opened 2018-05-15 23:09 UTC
#### Submission type

  - Bug report

#### Info regarding which version of Calamares is used, which Distribution

> KaOS 2018.04

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

> Went with the "erase disk"-option. Made no changes to anything.

- blkid: https://pastebin.com/ZBwShuUE
- fdisk -l: https://pastebin.com/0f4vMgWd

#### What do you expect to have happen when Calamares installs?

> That it works?

#### Describe the issue you encountered

> Error in Boost.Python job bootldr: https://drive.google.com/file/d/1byQNBKtiw08_sLNzyXplf3unLXQ1n17n/view?usp=sharing

#### Steps to reproduce the problem

> Try to install KaOS 2018.04 in VMware Player (newest) with standard settings for "other linux 4.x or later kernel 64-bit" settings

#### Include the installation.log (usually ~/Calamares/Calamares/Calamares.log, of the user Calamares runs as):

> https://pastebin.com/Ac80CBw7

I wanted to post this in the KaOS forums but the login doesn't work in Chrome and Firefox...

I found multiple Boost.Python job bootldr bugs by googling but these always talk about certain partition setups while I didn't change anything from the default settings. In the VMware Player I just changed the RAM to 10.088 GB and the CD to the ISO (sha256 is correct). I just chose to erase the drive in Calamares.
When I go into Octopi and click on SysInfo I just get a blank window: https://drive.google.com/file/d/1qi5gGRHK9HbsE4cS248kVSXCcUj9ojZ3/view?usp=sharing
When I shut down after the failed installation there are a few "warnings": https://drive.google.com/file/d/1sxKCeVdSc78oCaDmFZDxPrYErpkHUaPV/view?usp=sharing

**Comment by demmm** [comment] 2018-05-17 20:46
As side note, can you explain the forum login issue?  Using a github account or forum created account?

As for the bootldr failure, just to be sure, is this a BIOS system setup with ms-dos partition table? Or GPT?

**Comment by ShalokShalom** [comment] 2018-05-17 20:49
This is a BIOS system here and I experience the same: https://pastebin.com/tFAMEmwE

blkid: https://pastebin.com/raw/ULGvLSzj
fdisk -l https://pastebin.com/XPs4atTZ

**Comment by demmm** [comment] 2018-05-17 21:43
@ShalokShalom might be better to open a new report for your issue, since the initial report is about vmware & automated erase option, probably easier to debug in separate issues.

**Comment by FelixKainz** [comment] 2018-05-17 22:55
Well, I don't know where I should open a report for the login issue, so I'll just drop this here for now.
When I click on signup at https://forum.kaosx.us/ I choose one of the methods and sign in. Then, [this empty "window"](https://drive.google.com/file/d/1Vw9S1tTEEAHCFb5zp2-6MGvcy5M4Ev06/view?usp=sharing) appears. The same happens when I try to login with these 3rd (or 2nd?) partys.
When I then try to sign in with my email I get [this message](https://drive.google.com/file/d/13B21-6sBc4qqslxQrxemkpu0i8hIlCBj/view?usp=sharing).
I don't use any form of firewall.

This exact issue happens with both git and google log in. Happens in Firefox, Chrome and Edge "reliably".
BTW it says "**Login** with Google" but "**Log In** with GitHub" :P

Also I'm confused now. Why do I have 3 ways to log in but only two to sign up?


But back to the main issue.
I never thought about if my VM uses BIOS or EFI. VirtualBox has a toggle for that but I never saw something like that in the VMware Player. That means I don't know but shouldn't Calamares create it's own partition table when I choose to erase anything?

Everyone shoud be able to easily recreate this issue (actually both issues) as you just have to keep the default settings of a new VM in VMware Player as described in the initial post.

I just installed a new `Manjaro 17.1.10` VM which also uses Calamares and it went through with no problems. But Manjaro uses version `3.1.13-1` and KaOS uses `3.2.0rc4.20180427-git-master-68fc673`.

I think I will give VirtualBox a shot tomorrow since linux416 includes almost all guest additions and supports iGPU passthrough now.

**Comment by demmm** [comment] 2018-05-17 23:10
For the forum, please try again now, I enabled regular user creation option again (causes a lot of forum spam, thus disabled most of the time.  If that doesn't fix, please continue for that with a bug report at:
https://github.com/KaOSx/kaosx.github.io
https://github.com/KaOSx/kaosx.github.io/issues

Vmware is not in the KaOS repos, thus cannot be easily reproduced, that is why trying to find out where it fails.
KaOS uses systemd-boot for UEFI systems, and is the only distro using calamares that does so, so you can't compare other distros in this if you use UEFI.

**Comment by FelixKainz** [comment] 2018-05-17 23:27
I don't see where I can sign up besides through Google or GitHub.
VMware Player can be downloaded [here](https://my.vmware.com/en/web/vmware/free#desktop_end_user_computing/vmware_workstation_player/14_0) for Linux.  I don't know if there is any work like compilation required.

**Comment by ShalokShalom** [comment] 2018-05-17 23:33
You find the sign up menu under the password restore option. :)

**Comment by ShalokShalom** [comment] 2018-05-17 23:34
And you see in the partition menu of Calamares, if you are in BIOS or UEFI

**Comment by FelixKainz** [comment] 2018-05-17 23:38
I feel like it is the 1st of April now... ;D
Do you mean the "Forgot Password?" option? When I click on that I am prompted to enter my email. When I do so it says this email is unknown.

Anyway, I'll go to sleep now. It's 2 AM where I live...

**Comment by ShalokShalom** [comment] 2018-05-18 00:07
'Below' is what I mean with 'under'

**Comment by demmm** [comment] 2018-05-18 06:55
Please use the website repo for further forum issue discussions.  After the CSS change it probably will take your browser some time to clear the cache and show the third login option again.  If still not, clear the cache.  No further response here for this, use https://github.com/KaOSx/kaosx.github.io

Vmware will not be added to the repo for this bug report, so info will be needed in this report if the failure is UEFI or BIOS system related.

**Comment by FelixKainz** [comment] 2018-05-18 16:48
One last update about the login issue: It's gone...
Yesterday there was no signup with email, now there is. But I tried to sign up with GitHub and Google and both work.
Interesting...

I just tried to install KaOS in VIrtualBox. The same error happens when I try to install it in a BIOS (ms-dos) system. When I select EFI (GPT) in the VM's settings it works perfectly fine.
That means you can debug it with VirtualBox in it's default BIOS mode too.

**Comment by demmm** [comment] 2018-05-18 16:54
Well, this would be great news....
It has up to not been possible to install in UEFI mode in virtualbox for KaOS.
In BIOS mode, your setup is constantly tested, so this is with which version of virtualbox? 5.2.12?

As for the forum, I guess I will have to find another way to stop spammers, not showing the regular user creation option is causing too many errors.

**Comment by FelixKainz** [comment] 2018-05-18 17:55
Maybe putting a captcha next to any post-related button? ;D

It worked with 5.2.12, yes. Only in EFI mode tho. Default settings for "Other Linux (64-Bit) but CD -> ISO, RAM to 10G and core count to 6.

How come that the known problematic way works but the other one doesn't?

**Comment by FelixKainz** [comment] 2018-05-18 18:39
Just installed KaOS in a Vmware Player-VM in EFI mode. Works too.
But I got this warning I also got in VB: https://drive.google.com/file/d/1V7yhSI7uHa_feDtE0hqXlT-Lhw9RMEl6/view?usp=sharing
Is that normal?

**Comment by demmm** [comment] 2018-05-18 19:04
Yes that is normal, just a warning for some for rare modules.
Can you post the installation.log from that UEFI install in vmware (/varlog/installation.log)?

**Comment by FelixKainz** [comment] 2018-05-18 19:45
installation.log of
VMware Player EFI working: https://pastebin.com/LcWJjuky



Interestingly, bridged network connecton doesn't work anymore after updating via octopi in VMware.
another thing I've observed is that VB takes a long time to boot. It says 
`starting version 258`
`/`

**Comment by demmm** [comment] 2018-05-18 19:55
Log shows an error (imo) regarding removal of drivers.  It removed the vmware driver, that might be the cause of the slow boot.  What driver was used in live mode? What is used now?  `inxi -G` in both live & installed would be really helpful. 
Slow boot is also caused by ksplash 5.12, you can disable using any splashscreen in an X session to speed it up a lot.  Or use a Wayland session, no ksplash slowdown at all then.

**Comment by FelixKainz** [comment] 2018-05-18 20:32
It removed an VMware driver? But VB is the slow one. That shouldn't distract VB, shouldn't it?

In VMware it is VMware SVGA II Adapter.
[Live.](https://drive.google.com/file/d/1_1h07gZ-6Uh-rVEGX59TaZzWYxmg2oKx/view?usp=sharing)
[Delayed? ;D](https://drive.google.com/file/d/19MgpfpDNPYx32ZEFyjwr3ZXHfMO8HT9A/view?usp=sharing)

In VB it is InnoTek Systemberatung VirtualBox Graphics Adapter.
[Live](https://drive.google.com/file/d/1xxpxtvYOmdQmMyHzoBWXlOTGDt9_yVqA/view?usp=sharing).
[Normal](https://drive.google.com/file/d/1uWmQgFLfxnTKQ9KG226ZXzDZtxXKHH1k/view?usp=sharing).

**Comment by demmm** [comment] 2018-05-20 23:13
Seems it can now be reproduced to get the bootldr error for BIOS systems.
Actually not a bootldr job error, but a faulty XFS filesystem setup for grub.  To confirm you have the same issue, you can try another install in vmware with BIOS, it will error out again, and check after the the failed install what grub sees for your root filesystem:
```
sudo grub-probe --device /dev/sda1
```
it should return xfs, but probably will return`unknown filesystem`
Now trying to figure if this is a bug in calamares' partitioning or if xsprogs 4.16 changed something that grub can't handle.....

**Comment by ShalokShalom** [comment] 2018-05-21 00:54
Thanks demm, you are great. As always

**Comment by demmm** [comment] 2018-05-21 06:43
It is an issue with xfsprogs 4.16 onward, downgrading any install to 4.15.1, results in grub-probe labeling an XFS partition correctly as xfs again, instead of `unknown filesystem`.
I'll try to find a fix in either grub for 4.16, or xfsprogs will have to move back to 4.15.1 for now.

**Comment by demmm** [comment] 2018-05-21 06:51
Found the bug report, changes that caused this:
http://savannah.gnu.org/bugs/?func=detailitem&item_id=48645

**Comment by FelixKainz** [comment] 2018-05-21 17:30
I also get `unknown filesystem`.

**Comment by FelixKainz** [comment] 2018-05-21 18:53
KaOS-2018.05.21-x86_64.iso fixed it for me too.
But there still is this issue that there is no account selected after first boot.
It works in EFI mode too.
If I read your earlyer comments right, you said that EFI shouldn't work at all. Is there an explanation now why it suddenly worked for me?

Unfortunately, the new plasma seems to still not support wayland in VMs. Animations are still extremely slow, which makes it unusable...

**Comment by FelixKainz** [comment] 2018-05-21 18:53
Should I close this issue now?

**Comment by demmm** [comment] 2018-05-21 19:10
Not closing yet, since no new stable ISO is out.

No idea why now, but with that test ISO, UEFI mode just works here now too in vbox.

For sddm, no user selected, please open a new issue (under apps), I have known about it, can't find the fix yet.  It is the KaOS specific sddm theme that causes that.
Same for other issues you found/may find, please open separate bug reports for them.

**Comment by ShalokShalom** [comment] 2018-05-21 21:11
There was a new version of vbox released recently, I guess they simply added support it

**Comment by ShalokShalom** [comment] 2018-05-22 06:06
Oh I see
Interesting ^.^

**Comment by demmm** [comment] 2018-06-27 19:44
New stable ISO is now available, thus issue is resolved.

**Closed by demmm** 2018-06-27 19:44 UTC
