### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by ghost** [KaOSx/calamares#74] opened 2016-11-15 21:47 UTC
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### KaOS ISO date you are having issues with or have a request for

> 16.11

#### How did you create the Live Media?

> Just used the ISO in VirtualBox

#### Did you check the md5sum of the downloaded ISO?

> Yes:
```
➜  Downloads md5sum KaOS-2016.11-x86_64.iso 
0f77dd6f579a1f1f62731fed16d14062  KaOS-2016.11-x86_64.iso
```

#### Describe the issue you encountered

> During the installation process I chose Spanish language and Spanish latinamercan keyboard. But after the installation, I rebooted and the login screen only has US keyboard (but the keyboard works correctly in spanish latinamerican), and all the system is in English Language.

#### Steps to reproduce the problem

> The previous question describes it. Here is a video of all the process: https://www.youtube.com/watch?v=22tCLeZmers
- 3:30 Language selection
- 4:55 Keyboard selection
- 11:20 Login screen

#### Include the installation.log:
 * Live mode: `~/installation.log`
 * Installed System: `/var/log/installation.log`

> http://pastebin.com/cNjMrRE7

**Comment by demmm** [comment] 2016-11-15 22:21
The log shows es being removed:
16:46:30 [0]: Running "chroot" ("/tmp/calamares-root-8tbkg35q", "pacman", "-Rddn", "--noconfirm", "kde-l10n-es")
Not clear if this is an issue with Bogota or the English keyboard used.
Can you post your /etc/locale.conf after this install?
And please open the debug window when selecting the language & locale (bottom left on the installer).
Show what info that creates on locale selection (if possible, take a screenshot in live mode of this).

**Comment by PapayaMedia** [comment] 2016-11-15 23:30
locale.conf: http://pastebin.com/e8ijz7FJ

As you can see, LANG variable is set to en_US.UTF-8, the rest of the variables are set to es_CO.UTF-8

I manually edited the file and changed that variable to es_CO.UTF-8, restarted the system and now it is in Spanish.

Here is a video of the installation process showing the debug information: https://www.youtube.com/watch?v=Av73f0htU5g

**Comment by demmm** [comment] 2016-11-15 23:38
I will try and reproduce too, but this looks like an upstream bug for calamares.  Locale settings where changed recently, looks like something does not "read" correct when setting the different keyboard layout.
If I can reproduce, then I'll create an upstream report, will link it back here.

**Comment by demmm** [comment] 2016-11-15 23:43
This is the merge I am referring too:
https://github.com/KaOSx/calamares/commit/a7b54c9630db7157bcdc2cc440a4c63d5ba9a1cc#diff-43819c6dbe35b84259388833497e48e6

**Comment by ShalokShalom** [comment] 2018-05-17 23:38
This can be closed?

**Comment by demmm** [comment] 2018-06-27 19:47
No further response from submitter, assuming this is now fixed.

**Closed by demmm** 2018-06-27 19:47 UTC
