### ISSUE TITLE
Required to install Nvidia driver despite selecting not non-free

### ISSUE THREAD

**Issue by kehugter** [KaOSx/calamares#69] opened 2016-03-26 12:49 UTC
Steps to reproduce
- As boot option I selected `Start KaOS Live`, which uses nouveau.
- Run `Install KaOS` from the live system
- In the installer's `Licence` tab, Nvidia's license agreement is a requirement to continue with the installation

Expected
- User shouldn't be forced to agree with Nvidia's license if non-free wasn't selected

**Comment by demmm** [comment] 2016-03-26 12:54
There is no such requirement.  Default is to continue without agreeing to any license, you hav to click accept only to get non-free nvidia in the target install.  This looks like a broken install media.  How did you create the media?  Did you check md5?

**Comment by kehugter** [comment] 2016-03-26 13:08
ISO: `KaOS-2016.03-x86_64.iso`, downloaded minutes ago
md5: `ffa294d57991ef01db20143b614a03f1`, matches
Installed on VirtualBox directly from the downloaded image.

System:
Debian stretch
Linux 4.3.0-1-amd64
VirtualBox 5.0.16_Debian

**Comment by demmm** [comment] 2016-03-26 18:19
Not a bug, closing

**Closed by demmm** 2016-03-26 18:19 UTC

**Comment by kehugter** [comment] 2016-03-26 19:59
`Next` should remain active, looks like a minor bug to me.
